services:
  # Database
  db:
    image: postgres:16-alpine
    container_name: cashflow-db-dev
    environment:
      POSTGRES_DB: cashflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cashflow_db_data:/var/lib/postgresql/data
    networks:
      - cashflow_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: cashflow-backend:dev
    container_name: cashflow-backend-dev
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/cashflow
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - cashflow_network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level debug

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: cashflow-frontend:dev
    container_name: cashflow-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_DEBUG=true
      - VITE_LOG_LEVEL=debug
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
      - /app/build
    depends_on:
      - backend
    networks:
      - cashflow_network
    command: sh -c "find . -name '*.js' -not -path './node_modules/*' -type f -delete 2>/dev/null || true && npm run dev -- --config vite.config.docker.ts --host --force"

  # Email testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: cashflow-mailhog-dev
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cashflow_network

volumes:
  cashflow_db_data:

networks:
  cashflow_network:
    name: cashflow_network
    driver: bridge
