"""Add missing fields to Party model

Revision ID: aa6fe1a15eaf
Revises: dd20ead4f4cb
Create Date: 2025-08-23 16:28:38.778091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa6fe1a15eaf'
down_revision = 'dd20ead4f4cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('parties', 'gst_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('parties', 'billing_address_line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('parties', 'billing_city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('parties', 'billing_state',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('parties', 'billing_country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('parties', 'shipping_city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('parties', 'shipping_state',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('parties', 'shipping_country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('parties', 'gst_registration_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('parties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('parties', 'type')
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'account_head')
    op.drop_column('payments', 'payment_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('account_head', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('payments', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('parties', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.alter_column('parties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('parties', 'gst_registration_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('parties', 'shipping_country',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parties', 'shipping_state',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parties', 'shipping_city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('parties', 'billing_country',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('parties', 'billing_state',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('parties', 'billing_city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('parties', 'billing_address_line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('parties', 'gst_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('parties', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
