version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-profitpath_prod}
    ports:
      - "5432:5432"
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profitpath-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      target: production
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-profitpath_prod}
      POSTGRES_DB: ${POSTGRES_DB:-profitpath_prod}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "false"
      LOG_LEVEL: WARNING
      CORS_ORIGINS: ${CORS_ORIGINS}
    env_file:
      - ../../backend/env.example
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - backend_prod_logs:/app/logs
    command: sh -c "python -u scripts/ensure_database.py && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - profitpath-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.optimized
      target: production
    ports:
      - "80:80"
      - "443:443"
    environment:
      VITE_API_URL: ${API_URL}
      VITE_APP_ENV: production
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - profitpath-prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  prod_db_data:
  backend_prod_logs:

networks:
  profitpath-prod-network:
    driver: bridge
