services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cashflow
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cashflow-network

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      target: development
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/cashflow
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
    env_file:
      - ../../backend/env.example
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
      - backend_cache:/app/.cache
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cashflow-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app
      - frontend_cache:/app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_APP_ENV: development
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cashflow-network

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - cashflow-network

volumes:
  db_data:
  backend_cache:
  frontend_cache:

networks:
  cashflow-network:
    driver: bridge
