apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitpath-backend
  namespace: profitpath-prod
  labels:
    app: profitpath-backend
    version: v1.48.4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profitpath-backend
  template:
    metadata:
      labels:
        app: profitpath-backend
        version: v1.48.4
    spec:
      containers:
      - name: backend
        image: profitpath-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: profitpath-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: profitpath-secrets
              key: secret-key
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "WARNING"
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: profitpath-config
              key: cors-origins
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitpath-frontend
  namespace: profitpath-prod
  labels:
    app: profitpath-frontend
    version: v1.48.4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profitpath-frontend
  template:
    metadata:
      labels:
        app: profitpath-frontend
        version: v1.48.4
    spec:
      containers:
      - name: frontend
        image: profitpath-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: profitpath-config
              key: api-url
        - name: VITE_APP_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
