apiVersion: v1
kind: Service
metadata:
  name: cashflow-backend-service
  namespace: cashflow-prod
  labels:
    app: cashflow-backend
spec:
  selector:
    app: cashflow-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cashflow-frontend-service
  namespace: cashflow-prod
  labels:
    app: cashflow-frontend
spec:
  selector:
    app: cashflow-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
